name: Build, Push and Deploy DS to DockerHub

on:
  workflow_dispatch:       
  pull_request:
    branches:
      - main 

  
  
env:
   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
   REPO_API: api-gateway
   REPO_CLIENT: client-service
   REPO_ACCOUNT: account-servi
 
  



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Effectuer le checkout du code
        uses: actions/checkout@v4

      - name: Installer Java 17
        uses: actions/setup-java@v3
        with:
         distribution: temurin

         java-version: '17'

          


      - name: Se connecter Ã  DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: ds-account-service
        run: |
          cd ds-account-service
          mvn clean package -DskipTests
          docker build -t $DOCKER_USERNAME/ds-account-service:latest .
          docker push $DOCKER_USERNAME/ds-account-service:latest
      - name: ds-api-gateway
        run: |
          cd ds-api-gateway
          mvn clean package -DskipTests
          docker build -t $DOCKER_USERNAME/ds-api-gateway:latest .
          docker push $DOCKER_USERNAME/ds-api-gateway:latest
      - name: ds-client-service
        run: |
          cd ds-client-service
          mvn clean package -DskipTests
          docker build -t $DOCKER_USERNAME/ds-client-service:latest .
          docker push $DOCKER_USERNAME/ds-client-service:latest




 


  deploy:
  
    needs: build
    name: Deploy All Services
    runs-on: ubuntu-latest
  
    steps:
      - name: Simulate deployment
        run: |
          echo "Simulating deployment of all services"
          

          
